version: "3.8"

services:
  api:
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - civiclink-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: civiclink
    ports:
      - "5432:5432"
    networks:
      - civiclink-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  civiclink-network:

volumes:
  postgres-data:
